# Generated by Django 2.2.5 on 2019-09-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carburant',
            old_name='nom_prenom',
            new_name='nomPrenom',
        ),
        migrations.RenameField(
            model_name='entretient',
            old_name='contact_name',
            new_name='contactName',
        ),
        migrations.RenameField(
            model_name='entretient',
            old_name='nom_prenom',
            new_name='nomPrenom',
        ),
    ]
