# Generated by Django 2.2.5 on 2019-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0002_auto_20190929_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretient',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
