# Generated by Django 2.2.5 on 2019-10-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0003_auto_20190929_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburant',
            name='telephoneBr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='telephonePv',
            field=models.CharField(max_length=100),
        ),
    ]
