# Generated by Django 2.2.5 on 2019-10-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0004_auto_20191003_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburant',
            name='alimentation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='compteAnalytique',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='nomPrenom',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='structure',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='telephoneBr',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='telephonePv',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='vehicule',
            field=models.CharField(max_length=500),
        ),
    ]
