# Generated by Django 2.2.5 on 2019-10-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0007_auto_20191003_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carburant',
            name='type',
        ),
        migrations.AddField(
            model_name='carburant',
            name='typeCarburant',
            field=models.CharField(choices=[('TPE', 'TPE'), ('Carnet', 'Carnet')], default='Diesel', max_length=30),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='alimentation',
            field=models.CharField(choices=[('TPE', 'TPE'), ('Carnet', 'Carnet')], max_length=20),
        ),
    ]
