# Generated by Django 2.2.5 on 2019-10-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0008_auto_20191003_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburant',
            name='typeCarburant',
            field=models.CharField(choices=[('TPE', 'TPE'), ('Carnet', 'Carnet')], max_length=30),
        ),
    ]
