# Generated by Django 2.2.5 on 2019-10-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0009_auto_20191003_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='traitementCarburant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometrageInitial', models.CharField(max_length=100)),
                ('kilometrageActuel', models.CharField(max_length=100)),
                ('kilometrageParcouru', models.CharField(max_length=100)),
                ('quantiteConsommee', models.CharField(max_length=100)),
                ('tauxConsomation', models.CharField(max_length=100)),
                ('montantAlimentation', models.CharField(max_length=100)),
                ('dateAlimentation', models.CharField(max_length=100)),
                ('nouveauKilometrage', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carburant',
            name='alimentation',
            field=models.CharField(choices=[('TPE', 'TPE'), ('Carnet', 'Carnet')], max_length=20, verbose_name='Alimentation'),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='compteAnalytique',
            field=models.CharField(choices=[('200000', 'DIRECTION GENERALE'), ('200001', 'MINISTERE ENERGIE'), ('200008', 'PROJET PHOSPHATES'), ('201000', 'DIRECTION CENTRALE AUDIT GROUP & CONFORMITE  (ADG) '), ('203000', "SURETE INTERNE DE L'ETABLISSEMENT"), ('204000', 'SYNDICAT NATIONAL SONATRACH'), ('206000', 'SONATRACH MANAGEMENT ACADEMY (SMA)'), ('210000', 'DCP RESSOURCES HUMAINES (RHU)'), ('220000', 'DCP STRATEGIE, PLANIFICATION & ECONOMIE (SPE)'), ('220001', 'Projet SH 2030'), ('220002', 'Projet logicielle de Tableaux de Bord et de Business Intelligence'), ('220003', 'Projet SAP '), ('220004', "Projet Transformation Digitale & Centre d'Innovation Conjoint"), ('230000', 'DCP FINANCES (FIN)'), ('240000', 'DIRECTION CENTRALE ACTIVITES CENTRALES SIEGE (ACT)'), ('241000', 'DIRECTION DEVELOPPEMENT DES INFRASTRUCTURES (DDI)'), ('242000', 'DIRECTION FINANCES SIEGE (DFS)'), ('243000', 'DIRECTION GESTION SIEGE & ANNEXES (DGSA)'), ('245000', 'DIRECTION HYGIENE & SECURITE (DHS-ACT)'), ('246000', 'DIRECTION PROJET NOUVEAUX CENTRES DE FORMATION (NCF-ACT)'), ('247000', 'CORDONNATEUR SIE/ACT'), ('248000', 'DIRECTION APPROVISIONNEMENT & CONTRATS (DAC) '), ('249000', ' DIRECTION PROJET DELOCALISATION DES ACTIVITES DE SONATRACH A LA NOUVELLE VILLE   DE HASSI MESSAOUD (DHM)'), ('250000', 'DIRECTION CENTRALE JURIDIQUE (JUR)'), ('260000', "DIR. CENTRALE  INFORMATIQUE & SYSTÈME D'INFORMATION (ISI)"), ('300000', 'DIRECTION CENTRALE DES MARCHES & LOGISTIQUE  (MLG)'), ('320000', 'SANTE SECURITE ENVIRONNEMENT (HSE)'), ('330000', 'DIRECTION CORPORATE BUSINESS DEVELOPPENT ET MARKETING (BDM)'), ('340000', 'RECHERCHE & DEVELOPPEMENT (RDT)'), ('Autre', 'Autre')], max_length=10, verbose_name='Compte Analytique'),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='nomPrenom',
            field=models.CharField(max_length=100, verbose_name='Nom Prénom'),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='structure',
            field=models.CharField(max_length=100, verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='telephoneBr',
            field=models.CharField(max_length=100, verbose_name='Téléphone de bureau'),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='telephonePv',
            field=models.CharField(max_length=100, verbose_name='Téléphone privé'),
        ),
        migrations.AlterField(
            model_name='carburant',
            name='typeCarburant',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Essence', 'Essence'), ('Super', 'Super')], max_length=30, verbose_name='Type Carburant'),
        ),
    ]
