# Generated by Django 2.2.5 on 2019-10-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0011_auto_20191011_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitementcarburant',
            name='dateAlimentation',
            field=models.DateField(verbose_name='Date Alimentation'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='kilometrageActuel',
            field=models.FloatField(max_length=100, verbose_name='Kilometrage Actuel'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='kilometrageInitial',
            field=models.FloatField(max_length=100, verbose_name='Kilométrage Initial'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='kilometrageParcouru',
            field=models.FloatField(max_length=100, verbose_name='Kilometrage Parcouru'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='montantAlimentation',
            field=models.FloatField(max_length=100, verbose_name='Montant Alimentation'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='nouveauKilometrage',
            field=models.FloatField(max_length=100, verbose_name='Nouveaux Kilométrage'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='quantiteConsommee',
            field=models.FloatField(max_length=100, verbose_name='Quantité Consommée'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='tauxConsomation',
            field=models.FloatField(max_length=100, verbose_name='Taux De Consomation'),
        ),
    ]
