# Generated by Django 2.2.5 on 2019-10-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0012_auto_20191012_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretient',
            name='kilometrage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='kilometrageActuel',
            field=models.FloatField(verbose_name='Kilometrage Actuel'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='kilometrageInitial',
            field=models.FloatField(verbose_name='Kilométrage Initial'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='kilometrageParcouru',
            field=models.FloatField(verbose_name='Kilometrage Parcouru'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='quantiteConsommee',
            field=models.FloatField(verbose_name='Quantité Consommée'),
        ),
        migrations.AlterField(
            model_name='traitementcarburant',
            name='tauxConsomation',
            field=models.FloatField(verbose_name='Taux De Consomation'),
        ),
    ]
