# Generated by Django 2.2.5 on 2019-10-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0013_auto_20191012_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entretient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
