# Generated by Django 2.2.5 on 2019-10-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0014_auto_20191012_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carburant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
